# Databricks notebook source
# MAGIC %md
# MAGIC # Operations Transformation Pipeline (Combined Reference)
# MAGIC
# MAGIC Combined silver + gold Lakeflow Declarative Pipeline source of truth.
# MAGIC
# MAGIC | File | Purpose |
# MAGIC |------|---------|
# MAGIC | `notebooks/ldp_silver_transformations.ipynb` | Silver pipeline (deploy to Databricks) |
# MAGIC | `notebooks/ldp_gold_transformations.ipynb` | Gold pipeline (deploy to Databricks) |
# MAGIC | `ldp_operations_transformations.py` | Synced reference copy of both notebooks |
# MAGIC
# MAGIC **Do not edit this file directly.** Update the notebooks, then run:
# MAGIC
# MAGIC ```bash
# MAGIC python scripts/sync_ldp_operations_transformations.py
# MAGIC ```
# MAGIC
# MAGIC Architecture: Bronze (ingest) → Silver materialized views (`refined`) → Gold materialized views (`serve`).
# COMMAND ----------
# MAGIC %md
# MAGIC ## Silver layer — `refined` schema
# COMMAND ----------
# MAGIC ## Configuration
# COMMAND ----------

CATALOG = "jm_databricks_learning_ws"
INGEST_SCHEMA = "ingest"
REFINED_SCHEMA = "refined"

INGEST = f"{CATALOG}.{INGEST_SCHEMA}"
REFINED = f"{CATALOG}.{REFINED_SCHEMA}"
SERVE_SCHEMA = "serve"

SERVE = f"{CATALOG}.{SERVE_SCHEMA}"
# COMMAND ----------
# MAGIC ## Imports
# COMMAND ----------

from pyspark import pipelines as dp
from pyspark.sql import DataFrame
from pyspark.sql.functions import (
    unix_timestamp,
    trunc,
    sum as spark_sum,
    sequence,
    min as spark_min,
    max as spark_max,
    expr,
    explode,
    date_format,
    countDistinct,
    count,
    coalesce,
    col,
    length,
    lit,
    regexp_extract,
    row_number,
    to_date,
    to_timestamp,
    trim,
    upper,
    when,
)
from pyspark.sql.types import LongType
from pyspark.sql.window import Window

VALID_PURCHASE_ORDER_STATUSES = ("CREATED", "CONFIRMED", "DELIVERED", "CANCELLED")
VALID_SALES_ORDER_STATUSES = ("CREATED", "CONFIRMED", "SHIPPED", "DELIVERED", "CANCELLED")
VALID_PRODUCTION_ORDER_STATUSES = ("PLANNED", "IN_PROGRESS", "COMPLETED", "CANCELLED")
VALID_DOWNTIME_REASONS = (
    "MAINTENANCE",
    "POWER_FAILURE",
    "MATERIAL_SHORTAGE",
    "MACHINE_FAILURE",
    "QUALITY_CHECK",
)
# COMMAND ----------
# MAGIC ## Shared transformation helpers
# MAGIC 
# MAGIC Reusable data-quality and cleansing functions for the silver layer.
# COMMAND ----------

def _dedupe_order_columns(df: DataFrame) -> list:
    """
    Build window ordering from ingest metadata columns that exist on the source table.

    bronze_row_id may only be present on transactional order tables (purchase_orders,
    sales_orders). Other sources use updated_at, Fivetran sync metadata, or dropDuplicates.
    """
    order_cols = []
    for column_name in (
        "bronze_row_id",
        "sys_updated_on",
        "updated_at",
        "_fivetran_synced",
        "created_at",
        "sys_created_on",
    ):
        if column_name in df.columns:
            order_cols.append(col(column_name).desc_nulls_last())
    return order_cols


def _dedupe_latest(df: DataFrame, business_key: str) -> DataFrame:
    """Keep the latest row per business key when duplicates exist."""
    order_cols = _dedupe_order_columns(df)
    if not order_cols:
        return df.dropDuplicates([business_key])
    window = Window.partitionBy(business_key).orderBy(*order_cols)
    return (
        df.withColumn("_row_num", row_number().over(window))
        .filter(col("_row_num") == 1)
        .drop("_row_num")
    )


def _dedupe_exact_rows(df: DataFrame, key_columns: list[str]) -> DataFrame:
    """Remove duplicate rows for batch WMS tables, keeping the latest ingest record."""
    order_cols = _dedupe_order_columns(df)
    if not order_cols:
        return df.dropDuplicates(key_columns)
    window = Window.partitionBy(*key_columns).orderBy(*order_cols)
    return (
        df.withColumn("_row_num", row_number().over(window))
        .filter(col("_row_num") == 1)
        .drop("_row_num")
    )


def _trim_string_columns(df: DataFrame, columns: list[str]) -> DataFrame:
    """Trim leading and trailing whitespace on string columns."""
    trimmed = df
    for column_name in columns:
        if column_name in trimmed.columns:
            trimmed = trimmed.withColumn(column_name, trim(col(column_name)))
    return trimmed


def _normalize_status(status_column: str):
    """Map common status variants to canonical ERP values and uppercase the remainder."""
    normalized = trim(col(status_column))
    return (
        when(normalized == "DELIVERD", lit("DELIVERED"))
        .when(normalized.rlike("(?i)^confirmed$"), lit("CONFIRMED"))
        .when(normalized.rlike("(?i)^shipped$"), lit("SHIPPED"))
        .when((normalized == "") | normalized.isNull(), lit(None))
        .otherwise(upper(normalized))
    )


def _parse_bronze_date(column_name: str):
    """Parse source date strings; invalid values become NULL without failing the pipeline."""
    raw = trim(col(column_name))
    iso_prefix = regexp_extract(raw, r"^(\d{4}-\d{2}-\d{2})", 1)
    return coalesce(
        when(raw.rlike(r"^\d{4}-\d{2}-\d{2}$"), to_date(raw, "yyyy-MM-dd")),
        when(raw.rlike(r"^\d{4}-\d{2}-\d{2}T"), to_date(raw, "yyyy-MM-dd'T'HH:mm:ss")),
        when(raw.rlike(r"^\d{2}/\d{2}/\d{4}$"), to_date(raw, "dd/MM/yyyy")),
        when(raw.rlike(r"^\d{2}-[A-Za-z]{3}-\d{4}$"), to_date(raw, "dd-MMM-yyyy")),
        when(length(iso_prefix) > 0, to_date(iso_prefix, "yyyy-MM-dd")),
    )


def _parse_positive_quantity(column_name: str):
    """Cast source quantity values and retain only strictly positive integers."""
    parsed = when(
        trim(col(column_name)).rlike(r"^-?\d+(\.\d+)?$"),
        trim(col(column_name)).cast("double").cast(LongType()),
    )
    return when(parsed > 0, parsed)


def _filter_non_null_key(df: DataFrame, key_column: str) -> DataFrame:
    """Drop rows with missing or blank primary/business identifiers."""
    return df.filter(col(key_column).isNotNull() & (length(col(key_column)) > 0))


def _clean_master_stream(
    source_df: DataFrame,
    business_key: str,
    string_columns: list[str],
) -> DataFrame:
    """Apply silver cleansing rules to ERP master tables."""
    cleaned = _trim_string_columns(source_df, string_columns)
    cleaned = _filter_non_null_key(cleaned, business_key)
    return _dedupe_latest(cleaned, business_key)


def _clean_order_stream(
    source_df: DataFrame,
    business_key: str,
    string_columns: list[str],
    delivery_date_column: str,
    valid_statuses: tuple[str, ...],
) -> DataFrame:
    """Apply silver cleansing rules to ERP purchase and sales orders."""
    cleaned = _trim_string_columns(source_df, string_columns)
    cleaned = _filter_non_null_key(cleaned, business_key)
    cleaned = _dedupe_latest(cleaned, business_key)

    cleaned = (
        cleaned.withColumn("status", _normalize_status("status"))
        .withColumn("order_date", _parse_bronze_date("order_date"))
        .withColumn(delivery_date_column, _parse_bronze_date(delivery_date_column))
        .withColumn("quantity", _parse_positive_quantity("quantity"))
    )

    cleaned = cleaned.filter(col("quantity").isNotNull())

    cleaned = cleaned.withColumn(
        "status",
        when(col("status").isin(*valid_statuses), col("status")).otherwise(upper(col("status"))),
    )

    return cleaned


def _enforce_foreign_key(
    df: DataFrame,
    foreign_key: str,
    master_df: DataFrame,
    master_key: str,
) -> DataFrame:
    """Drop rows whose foreign key is missing from the cleaned master table."""
    valid_keys = master_df.select(master_key).distinct()
    if foreign_key == master_key:
        return df.join(valid_keys, on=foreign_key, how="left_semi")
    return df.join(
        valid_keys,
        df[foreign_key] == valid_keys[master_key],
        how="left_semi",
    )


def _enforce_material_type(
    df: DataFrame,
    materials_df: DataFrame,
    *,
    material_type: str,
) -> DataFrame:
    """Drop rows that reference materials of the wrong type or not in the master list."""
    valid_materials = (
        materials_df.filter(col("material_type") == material_type)
        .select("material_id")
        .distinct()
    )
    return df.join(valid_materials, on="material_id", how="inner")


def _clean_purchase_orders(
    source_df: DataFrame,
    suppliers_df: DataFrame,
    materials_df: DataFrame,
) -> DataFrame:
    """Clean purchase orders and retain only rows with valid supplier and raw material FKs."""
    cleaned = _clean_order_stream(
        source_df,
        business_key="purchase_order_id",
        string_columns=[
            "purchase_order_id",
            "supplier_id",
            "material_id",
            "status",
            "order_date",
            "expected_delivery_date",
            "quantity",
        ],
        delivery_date_column="expected_delivery_date",
        valid_statuses=VALID_PURCHASE_ORDER_STATUSES,
    )
    cleaned = _enforce_foreign_key(cleaned, "supplier_id", suppliers_df, "supplier_id")
    return _enforce_material_type(cleaned, materials_df, material_type="RAW_MATERIAL")


def _clean_sales_orders(
    source_df: DataFrame,
    customers_df: DataFrame,
    materials_df: DataFrame,
) -> DataFrame:
    """Clean sales orders and retain only rows with valid customer and finished-good FKs."""
    cleaned = _clean_order_stream(
        source_df,
        business_key="sales_order_id",
        string_columns=[
            "sales_order_id",
            "customer_id",
            "material_id",
            "status",
            "order_date",
            "requested_delivery_date",
            "quantity",
        ],
        delivery_date_column="requested_delivery_date",
        valid_statuses=VALID_SALES_ORDER_STATUSES,
    )
    cleaned = _enforce_foreign_key(cleaned, "customer_id", customers_df, "customer_id")
    return _enforce_material_type(cleaned, materials_df, material_type="FINISHED_GOOD")


def _clean_inventory_with_masters(
    source_df: DataFrame,
    warehouses_df: DataFrame,
    materials_df: DataFrame,
) -> DataFrame:
    """Clean inventory snapshots and retain only rows with valid warehouse and material FKs."""
    cleaned = _clean_inventory_batch(source_df)
    cleaned = _enforce_foreign_key(cleaned, "warehouse_id", warehouses_df, "warehouse_id")
    return _enforce_foreign_key(cleaned, "material_id", materials_df, "material_id")


def _clean_inventory_batch(source_df: DataFrame) -> DataFrame:
    """Silver rules for Fivetran WMS inventory snapshots."""
    string_columns = ["warehouse_id", "material_id", "quantity", "snapshot_date"]
    cleaned = _trim_string_columns(source_df, string_columns)
    cleaned = cleaned.filter(
        col("warehouse_id").isNotNull()
        & (length(col("warehouse_id")) > 0)
        & col("material_id").isNotNull()
        & (length(col("material_id")) > 0)
        & col("snapshot_date").isNotNull()
        & (length(col("snapshot_date")) > 0)
    )
    cleaned = cleaned.withColumn(
        "quantity",
        _parse_positive_quantity("quantity"),
    )
    cleaned = cleaned.filter(col("quantity").isNotNull())
    cleaned = cleaned.withColumn("snapshot_date", to_date(col("snapshot_date")))
    cleaned = _dedupe_exact_rows(cleaned, ["snapshot_date", "warehouse_id", "material_id"])
    return cleaned


def _clean_inventory_transactions_with_masters(
    source_df: DataFrame,
    warehouses_df: DataFrame,
    materials_df: DataFrame,
) -> DataFrame:
    """Clean inventory transactions and retain only rows with valid warehouse and material FKs."""
    cleaned = _clean_inventory_transactions_batch(source_df)
    cleaned = _enforce_foreign_key(cleaned, "warehouse_id", warehouses_df, "warehouse_id")
    return _enforce_foreign_key(cleaned, "material_id", materials_df, "material_id")


def _clean_inventory_transactions_batch(source_df: DataFrame) -> DataFrame:
    """Silver rules for Fivetran WMS inventory transactions."""
    string_columns = [
        "transaction_id",
        "transaction_date",
        "warehouse_id",
        "material_id",
        "transaction_type",
        "quantity",
        "reference_id",
    ]
    cleaned = _trim_string_columns(source_df, string_columns)
    cleaned = cleaned.filter(
        col("transaction_id").isNotNull()
        & (length(col("transaction_id")) > 0)
        & col("warehouse_id").isNotNull()
        & (length(col("warehouse_id")) > 0)
        & col("material_id").isNotNull()
        & (length(col("material_id")) > 0)
        & col("transaction_type").isNotNull()
        & (length(col("transaction_type")) > 0)
    )
    cleaned = cleaned.withColumn("transaction_type", upper(col("transaction_type")))
    cleaned = cleaned.withColumn("quantity", _parse_positive_quantity("quantity"))
    cleaned = cleaned.filter(col("quantity").isNotNull())
    cleaned = _dedupe_exact_rows(cleaned, ["transaction_id"])
    return cleaned


def _normalize_ingest_column_names(df: DataFrame) -> DataFrame:
    """Rename quoted or case-variant ingest columns to canonical lowercase names."""
    if not df.columns:
        return df
    return df.select(
        *[
            col(field.name).alias(field.name.strip('"').strip("`").lower())
            for field in df.schema.fields
        ]
    )


def _apply_column_aliases(df: DataFrame, aliases: dict[str, list[str]]) -> DataFrame:
    """Map connector-specific column names onto canonical schema fields."""
    normalized = _normalize_ingest_column_names(df)
    for canonical, candidates in aliases.items():
        existing = [name for name in candidates if name in normalized.columns]
        if not existing:
            continue
        normalized = normalized.withColumn(
            canonical,
            coalesce(*[col(name) for name in existing]),
        )
    return normalized


def _parse_bronze_timestamp(column_name: str):
    """Parse source timestamp strings; invalid values become NULL."""
    raw = trim(col(column_name))
    return coalesce(
        when(raw.rlike(r"^\d{4}-\d{2}-\d{2}T"), to_timestamp(raw, "yyyy-MM-dd'T'HH:mm:ss")),
        when(raw.rlike(r"^\d{4}-\d{2}-\d{2} "), to_timestamp(raw, "yyyy-MM-dd HH:mm:ss")),
        when(raw.rlike(r"^\d{4}-\d{2}-\d{2}$"), to_timestamp(raw, "yyyy-MM-dd")),
        when(raw.rlike(r"^\d{2}/\d{2}/\d{4}"), to_timestamp(raw, "dd/MM/yyyy HH:mm:ss")),
    )


def _parse_optional_positive_quantity(column_name: str):
    """Cast optional quantity values and retain only strictly positive integers."""
    parsed = when(
        trim(col(column_name)).rlike(r"^-?\d+(\.\d+)?$"),
        trim(col(column_name)).cast("double").cast(LongType()),
    )
    return when(parsed > 0, parsed)


def _clean_production_orders(
    source_df: DataFrame,
    plants_df: DataFrame,
    materials_df: DataFrame,
) -> DataFrame:
    """Clean production orders from Snowflake ingest.

    Snowflake ingest may expose quoted lowercase columns such as
    `"production_order_id"`; these are normalized before cleansing.
    """
    source_df = _normalize_ingest_column_names(source_df)
    aliases = {
        "production_order_id": ["production_order_id", "PRODUCTION_ORDER_ID"],
        "plant_id": ["plant_id", "PLANT_ID"],
        "material_id": ["material_id", "MATERIAL_ID"],
        "planned_quantity": ["planned_quantity", "PLANNED_QUANTITY"],
        "actual_quantity": ["actual_quantity", "ACTUAL_QUANTITY"],
        "start_date": ["start_date", "START_DATE"],
        "end_date": ["end_date", "END_DATE"],
        "status": ["status", "STATUS"],
    }
    cleaned = _apply_column_aliases(source_df, aliases)
    cleaned = _trim_string_columns(
        cleaned,
        [
            "production_order_id",
            "plant_id",
            "material_id",
            "status",
            "start_date",
            "end_date",
            "planned_quantity",
            "actual_quantity",
        ],
    )
    cleaned = _filter_non_null_key(cleaned, "production_order_id")
    cleaned = _dedupe_latest(cleaned, "production_order_id")
    cleaned = (
        cleaned.withColumn("status", _normalize_status("status"))
        .withColumn("start_date", _parse_bronze_date("start_date"))
        .withColumn("end_date", _parse_bronze_date("end_date"))
        .withColumn("planned_quantity", _parse_positive_quantity("planned_quantity"))
        .withColumn("actual_quantity", _parse_optional_positive_quantity("actual_quantity"))
    )
    cleaned = cleaned.filter(col("planned_quantity").isNotNull())
    cleaned = cleaned.withColumn(
        "status",
        when(col("status").isin(*VALID_PRODUCTION_ORDER_STATUSES), col("status")).otherwise(
            upper(col("status"))
        ),
    )
    cleaned = _enforce_foreign_key(cleaned, "plant_id", plants_df, "plant_id")
    return _enforce_material_type(cleaned, materials_df, material_type="FINISHED_GOOD")


def _clean_production_output(
    source_df: DataFrame,
    production_orders_df: DataFrame,
    materials_df: DataFrame,
) -> DataFrame:
    """Clean production output from Snowflake ingest.

    Snowflake ingest may expose quoted lowercase columns such as
    `"production_output_id"`; these are normalized before cleansing.
    """
    source_df = _normalize_ingest_column_names(source_df)
    aliases = {
        "production_output_id": ["production_output_id", "PRODUCTION_OUTPUT_ID"],
        "production_order_id": ["production_order_id", "PRODUCTION_ORDER_ID"],
        "input_material_id": ["input_material_id", "INPUT_MATERIAL_ID"],
        "input_quantity": ["input_quantity", "INPUT_QUANTITY"],
        "output_material_id": ["output_material_id", "OUTPUT_MATERIAL_ID"],
        "output_quantity": ["output_quantity", "OUTPUT_QUANTITY"],
    }
    cleaned = _apply_column_aliases(source_df, aliases)
    cleaned = _trim_string_columns(
        cleaned,
        [
            "production_output_id",
            "production_order_id",
            "input_material_id",
            "input_quantity",
            "output_material_id",
            "output_quantity",
        ],
    )
    cleaned = _filter_non_null_key(cleaned, "production_output_id")
    cleaned = _dedupe_latest(cleaned, "production_output_id")
    cleaned = (
        cleaned.withColumn("input_quantity", _parse_positive_quantity("input_quantity"))
        .withColumn("output_quantity", _parse_positive_quantity("output_quantity"))
    )
    cleaned = cleaned.filter(
        col("input_quantity").isNotNull() & col("output_quantity").isNotNull()
    )
    cleaned = _enforce_foreign_key(
        cleaned, "production_order_id", production_orders_df, "production_order_id"
    )
    valid_raw_materials = (
        materials_df.filter(col("material_type") == "RAW_MATERIAL")
        .select(col("material_id").alias("input_material_id"))
        .distinct()
    )
    valid_finished_goods = (
        materials_df.filter(col("material_type") == "FINISHED_GOOD")
        .select(col("material_id").alias("output_material_id"))
        .distinct()
    )
    cleaned = cleaned.join(valid_raw_materials, on="input_material_id", how="inner")
    return cleaned.join(valid_finished_goods, on="output_material_id", how="inner")


def _clean_machine_downtime(source_df: DataFrame, plants_df: DataFrame) -> DataFrame:
    """Clean machine downtime events from ServiceNow ingest."""
    cleaned = source_df
    if "_databricks_deleted" in cleaned.columns:
        cleaned = cleaned.filter(
            col("_databricks_deleted").isNull() | (col("_databricks_deleted") == lit(False))
        )

    aliases = {
        "downtime_id": ["u_downtime_id", "downtime_id"],
        "plant_id": ["u_plant_id", "plant_id"],
        "machine_name": ["u_machine_name", "machine_name"],
        "start_time": ["u_start_time", "start_time"],
        "end_time": ["u_end_time", "end_time"],
        "reason": ["u_reason", "reason"],
    }
    cleaned = _apply_column_aliases(cleaned, aliases)
    cleaned = _trim_string_columns(
        cleaned,
        ["downtime_id", "plant_id", "machine_name", "reason"],
    )
    cleaned = _filter_non_null_key(cleaned, "downtime_id")
    cleaned = _dedupe_latest(cleaned, "downtime_id")
    cleaned = (
        cleaned.withColumn("machine_name", trim(col("machine_name")))
        .withColumn("reason", upper(trim(col("reason"))))
        .withColumn("start_time", to_timestamp(col("start_time")))
        .withColumn("end_time", to_timestamp(col("end_time")))
    )
    cleaned = cleaned.filter(col("start_time").isNotNull() & col("end_time").isNotNull())
    cleaned = cleaned.withColumn(
        "reason",
        when(col("reason").isin(*VALID_DOWNTIME_REASONS), col("reason")).otherwise(
            upper(col("reason"))
        ),
    )
    return _enforce_foreign_key(cleaned, "plant_id", plants_df, "plant_id")
# COMMAND ----------
# MAGIC ## ERP master data (materialized views)
# COMMAND ----------

@dp.materialized_view(
    name=f"{REFINED}.customers",
    comment="Cleaned customer master from ingest.customers",
    table_properties={"quality": "silver", "domain": "erp"},
)
@dp.expect_or_drop("valid_customer_id", "customer_id IS NOT NULL AND length(trim(customer_id)) > 0")
def refined_customers():
    return _clean_master_stream(
        spark.read.table(f"{INGEST}.customers"),
        business_key="customer_id",
        string_columns=["customer_id", "customer_name", "country"],
    )


@dp.materialized_view(
    name=f"{REFINED}.materials",
    comment="Cleaned material master from ingest.materials",
    table_properties={"quality": "silver", "domain": "erp"},
)
@dp.expect_or_drop("valid_material_id", "material_id IS NOT NULL AND length(trim(material_id)) > 0")
def refined_materials():
    cleaned = _clean_master_stream(
        spark.read.table(f"{INGEST}.materials"),
        business_key="material_id",
        string_columns=["material_id", "material_name", "material_type"],
    )
    # Normalize material_type to uppercase canonical values.
    return cleaned.withColumn("material_type", upper(col("material_type")))


@dp.materialized_view(
    name=f"{REFINED}.plants",
    comment="Cleaned plant master from ingest.plants",
    table_properties={"quality": "silver", "domain": "erp"},
)
@dp.expect_or_drop("valid_plant_id", "plant_id IS NOT NULL AND length(trim(plant_id)) > 0")
def refined_plants():
    return _clean_master_stream(
        spark.read.table(f"{INGEST}.plants"),
        business_key="plant_id",
        string_columns=["plant_id", "plant_name", "country"],
    )


@dp.materialized_view(
    name=f"{REFINED}.suppliers",
    comment="Cleaned supplier master from ingest.suppliers",
    table_properties={"quality": "silver", "domain": "erp"},
)
@dp.expect_or_drop("valid_supplier_id", "supplier_id IS NOT NULL AND length(trim(supplier_id)) > 0")
def refined_suppliers():
    return _clean_master_stream(
        spark.read.table(f"{INGEST}.suppliers"),
        business_key="supplier_id",
        string_columns=["supplier_id", "supplier_name", "country"],
    )


@dp.materialized_view(
    name=f"{REFINED}.warehouses",
    comment="Cleaned warehouse master from ingest.warehouses",
    table_properties={"quality": "silver", "domain": "erp"},
)
@dp.expect_or_drop("valid_warehouse_id", "warehouse_id IS NOT NULL AND length(trim(warehouse_id)) > 0")
def refined_warehouses():
    cleaned = _clean_master_stream(
        spark.read.table(f"{INGEST}.warehouses"),
        business_key="warehouse_id",
        string_columns=["warehouse_id", "warehouse_name", "plant_id"],
    )
    plants = spark.read.table(f"{REFINED}.plants")
    return _enforce_foreign_key(cleaned, "plant_id", plants, "plant_id")
# COMMAND ----------
# MAGIC ## ERP transactional data (materialized views)
# COMMAND ----------

@dp.materialized_view(
    name=f"{REFINED}.purchase_orders",
    comment="Deduped and validated purchase orders from ingest.purchase_orders",
    table_properties={"quality": "silver", "domain": "erp"},
)
@dp.expect_or_drop(
    "valid_purchase_order_id",
    "purchase_order_id IS NOT NULL AND length(trim(purchase_order_id)) > 0",
)
@dp.expect_or_drop("positive_quantity", "quantity IS NOT NULL AND quantity > 0")
@dp.expect_or_drop("valid_supplier_id", "supplier_id IS NOT NULL AND length(trim(supplier_id)) > 0")
@dp.expect_or_drop("valid_material_id", "material_id IS NOT NULL AND length(trim(material_id)) > 0")
def refined_purchase_orders():
    suppliers = spark.read.table(f"{REFINED}.suppliers")
    materials = spark.read.table(f"{REFINED}.materials")
    return _clean_purchase_orders(
        spark.read.table(f"{INGEST}.purchase_orders"),
        suppliers,
        materials,
    )


@dp.materialized_view(
    name=f"{REFINED}.sales_orders",
    comment="Deduped and validated sales orders from ingest.sales_orders",
    table_properties={"quality": "silver", "domain": "erp"},
)
@dp.expect_or_drop(
    "valid_sales_order_id",
    "sales_order_id IS NOT NULL AND length(trim(sales_order_id)) > 0",
)
@dp.expect_or_drop("positive_quantity", "quantity IS NOT NULL AND quantity > 0")
@dp.expect_or_drop("valid_customer_id", "customer_id IS NOT NULL AND length(trim(customer_id)) > 0")
@dp.expect_or_drop("valid_material_id", "material_id IS NOT NULL AND length(trim(material_id)) > 0")
def refined_sales_orders():
    customers = spark.read.table(f"{REFINED}.customers")
    materials = spark.read.table(f"{REFINED}.materials")
    return _clean_sales_orders(
        spark.read.table(f"{INGEST}.sales_orders"),
        customers,
        materials,
    )
# COMMAND ----------
# MAGIC ## WMS data (batch)
# COMMAND ----------

@dp.materialized_view(
    name=f"{REFINED}.inventory",
    comment="Cleaned daily inventory snapshots from ingest.inventory",
    table_properties={"quality": "silver", "domain": "wms"},
)
@dp.expect_or_drop("positive_quantity", "quantity IS NOT NULL AND quantity > 0")
def refined_inventory():
    warehouses = spark.read.table(f"{REFINED}.warehouses")
    materials = spark.read.table(f"{REFINED}.materials")
    return _clean_inventory_with_masters(
        spark.read.table(f"{INGEST}.inventory"),
        warehouses,
        materials,
    )


@dp.materialized_view(
    name=f"{REFINED}.inventory_transactions",
    comment="Cleaned inventory transactions from ingest.inventory_transactions",
    table_properties={"quality": "silver", "domain": "wms"},
)
@dp.expect_or_drop("positive_quantity", "quantity IS NOT NULL AND quantity > 0")
def refined_inventory_transactions():
    warehouses = spark.read.table(f"{REFINED}.warehouses")
    materials = spark.read.table(f"{REFINED}.materials")
    return _clean_inventory_transactions_with_masters(
        spark.read.table(f"{INGEST}.inventory_transactions"),
        warehouses,
        materials,
    )
# COMMAND ----------
# MAGIC ## MES data (Snowflake + ServiceNow)
# COMMAND ----------

@dp.materialized_view(
    name=f"{REFINED}.production_orders",
    comment="Cleaned production orders from ingest.production_orders (Snowflake)",
    table_properties={"quality": "silver", "domain": "mes"},
)
@dp.expect_or_drop(
    "valid_production_order_id",
    "production_order_id IS NOT NULL AND length(trim(production_order_id)) > 0",
)
@dp.expect_or_drop("positive_planned_quantity", "planned_quantity IS NOT NULL AND planned_quantity > 0")
def refined_production_orders():
    plants = spark.read.table(f"{REFINED}.plants")
    materials = spark.read.table(f"{REFINED}.materials")
    return _clean_production_orders(
        spark.read.table(f"{INGEST}.production_orders"),
        plants,
        materials,
    )


@dp.materialized_view(
    name=f"{REFINED}.production_output",
    comment="Cleaned production output from ingest.production_output (Snowflake)",
    table_properties={"quality": "silver", "domain": "mes"},
)
@dp.expect_or_drop(
    "valid_production_output_id",
    "production_output_id IS NOT NULL AND length(trim(production_output_id)) > 0",
)
@dp.expect_or_drop("positive_input_quantity", "input_quantity IS NOT NULL AND input_quantity > 0")
@dp.expect_or_drop("positive_output_quantity", "output_quantity IS NOT NULL AND output_quantity > 0")
def refined_production_output():
    production_orders = spark.read.table(f"{REFINED}.production_orders")
    materials = spark.read.table(f"{REFINED}.materials")
    return _clean_production_output(
        spark.read.table(f"{INGEST}.production_output"),
        production_orders,
        materials,
    )


@dp.materialized_view(
    name=f"{REFINED}.machine_downtime",
    comment="Cleaned machine downtime events from ingest.machine_downtime (ServiceNow)",
    table_properties={"quality": "silver", "domain": "mes"},
)
@dp.expect_or_drop(
    "valid_downtime_id",
    "downtime_id IS NOT NULL AND length(trim(downtime_id)) > 0",
)
def refined_machine_downtime():
    plants = spark.read.table(f"{REFINED}.plants")
    return _clean_machine_downtime(
        spark.read.table(f"{INGEST}.machine_downtime"),
        plants,
    )
# COMMAND ----------
# MAGIC %md
# MAGIC ## Gold layer — `serve` schema
# COMMAND ----------
# MAGIC ## Helpers
# COMMAND ----------

def _full_month_spine(bounds_df, min_col="min_month", max_col="max_month"):
    """Build a continuous month spine from inclusive min/max month columns."""
    return bounds_df.filter(
        col(min_col).isNotNull() & col(max_col).isNotNull()
    ).select(
        explode(sequence(col(min_col), col(max_col), expr("interval 1 month"))).alias(
            "month_start_date"
        )
    )
# COMMAND ----------
# MAGIC ## `serve.supplier_summary`
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.supplier_summary",
    comment="Purchase order volume and quantity by supplier",
    table_properties={"quality": "gold", "domain": "procurement"},
)
def serve_supplier_summary():
    purchase_orders = spark.read.table(f"{REFINED}.purchase_orders")
    suppliers = spark.read.table(f"{REFINED}.suppliers")

    return (
        purchase_orders.join(suppliers, on="supplier_id", how="inner")
        .groupBy(
            col("supplier_id"),
            col("supplier_name"),
            col("country"),
        )
        .agg(
            count(lit(1)).alias("total_purchase_orders"),
            spark_sum("quantity").alias("total_quantity"),
        )
    )
# COMMAND ----------
# MAGIC ## `serve.customer_summary`
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.customer_summary",
    comment="Sales order volume and quantity by customer",
    table_properties={"quality": "gold", "domain": "sales"},
)
def serve_customer_summary():
    sales_orders = spark.read.table(f"{REFINED}.sales_orders")
    customers = spark.read.table(f"{REFINED}.customers")

    return (
        sales_orders.join(customers, on="customer_id", how="inner")
        .groupBy(
            col("customer_id"),
            col("customer_name"),
            col("country"),
        )
        .agg(
            count(lit(1)).alias("total_sales_orders"),
            spark_sum("quantity").alias("total_quantity"),
        )
    )
# COMMAND ----------
# MAGIC ## `serve.inventory_summary`
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.inventory_summary",
    comment="Current stock and material coverage by warehouse",
    table_properties={"quality": "gold", "domain": "inventory"},
)
def serve_inventory_summary():
    inventory = spark.read.table(f"{REFINED}.inventory")

    latest_snapshot = inventory.agg(spark_max("snapshot_date").alias("latest_snapshot_date"))
    current_inventory = inventory.join(
        latest_snapshot,
        inventory.snapshot_date == latest_snapshot.latest_snapshot_date,
        how="inner",
    ).drop("latest_snapshot_date")

    warehouses = spark.read.table(f"{REFINED}.warehouses")

    return (
        current_inventory.join(warehouses, on="warehouse_id", how="inner")
        .groupBy(
            col("warehouse_id"),
            col("warehouse_name"),
            col("plant_id"),
        )
        .agg(
            spark_sum("quantity").alias("current_stock"),
            countDistinct("material_id").alias("total_materials"),
        )
    )
# COMMAND ----------
# MAGIC ## `serve.material_summary`
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.material_summary",
    comment="Purchased, sold, and on-hand quantities by material",
    table_properties={"quality": "gold", "domain": "inventory"},
)
def serve_material_summary():
    purchase_orders = spark.read.table(f"{REFINED}.purchase_orders")
    sales_orders = spark.read.table(f"{REFINED}.sales_orders")
    inventory = spark.read.table(f"{REFINED}.inventory")
    materials = spark.read.table(f"{REFINED}.materials")

    purchased = purchase_orders.groupBy("material_id").agg(
        spark_sum("quantity").alias("purchased_quantity"),
    )

    sold = sales_orders.groupBy("material_id").agg(
        spark_sum("quantity").alias("sold_quantity"),
    )

    latest_snapshot = inventory.agg(spark_max("snapshot_date").alias("latest_snapshot_date"))
    current_inventory = (
        inventory.join(
            latest_snapshot,
            inventory.snapshot_date == latest_snapshot.latest_snapshot_date,
            how="inner",
        )
        .groupBy("material_id")
        .agg(spark_sum("quantity").alias("current_inventory"))
    )

    return (
        materials.select("material_id", "material_name", "material_type")
        .join(purchased, on="material_id", how="left")
        .join(sold, on="material_id", how="left")
        .join(current_inventory, on="material_id", how="left")
        .select(
            "material_id",
            "material_name",
            "material_type",
            coalesce(col("purchased_quantity"), lit(0)).alias("purchased_quantity"),
            coalesce(col("sold_quantity"), lit(0)).alias("sold_quantity"),
            coalesce(col("current_inventory"), lit(0)).alias("current_inventory"),
        )
    )
# COMMAND ----------
# MAGIC ## `serve.business_kpi_summary`
# MAGIC 
# MAGIC Single-row headline KPIs for dashboard counter widgets.
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.business_kpi_summary",
    comment="Headline business KPIs for dashboard counter widgets",
    table_properties={"quality": "gold", "domain": "executive"},
)
def serve_business_kpi_summary():
    purchase_orders = spark.read.table(f"{REFINED}.purchase_orders")
    sales_orders = spark.read.table(f"{REFINED}.sales_orders")
    inventory = spark.read.table(f"{REFINED}.inventory")

    active_purchase_orders = purchase_orders.filter(col("status") != "CANCELLED")
    active_sales_orders = sales_orders.filter(col("status") != "CANCELLED")

    latest_snapshot = inventory.agg(spark_max("snapshot_date").alias("inventory_snapshot_date"))
    current_inventory = inventory.join(
        latest_snapshot,
        inventory.snapshot_date == latest_snapshot.inventory_snapshot_date,
        how="inner",
    )

    purchase_stats = active_purchase_orders.agg(
        count(lit(1)).alias("total_purchase_orders"),
        countDistinct("supplier_id").alias("active_suppliers"),
    )
    sales_stats = active_sales_orders.agg(
        count(lit(1)).alias("total_sales_orders"),
        countDistinct("customer_id").alias("active_customers"),
    )
    inventory_stats = current_inventory.agg(
        coalesce(spark_sum("quantity"), lit(0)).alias("inventory_on_hand"),
    )

    return (
        purchase_stats.crossJoin(sales_stats)
        .crossJoin(inventory_stats)
        .crossJoin(latest_snapshot)
    )
# COMMAND ----------
# MAGIC ## `serve.sales_trend_monthly`
# MAGIC 
# MAGIC Monthly sales order volume across the full order history (line chart).
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.sales_trend_monthly",
    comment="Monthly sales order count and quantity for dashboard trend charts",
    table_properties={"quality": "gold", "domain": "sales"},
)
def serve_sales_trend_monthly():
    sales_orders = (
        spark.read.table(f"{REFINED}.sales_orders")
        .filter(col("status") != "CANCELLED")
        .filter(col("order_date").isNotNull())
    )

    bounds = sales_orders.agg(
        spark_min(trunc("order_date", "month")).alias("min_month"),
        spark_max(trunc("order_date", "month")).alias("max_month"),
    )
    months = _full_month_spine(bounds)

    monthly_totals = (
        sales_orders.withColumn("month_start_date", trunc("order_date", "month"))
        .groupBy("month_start_date")
        .agg(
            count(lit(1)).alias("order_count"),
            spark_sum("quantity").alias("total_quantity"),
        )
    )

    return (
        months.join(monthly_totals, on="month_start_date", how="left")
        .select(
            col("month_start_date"),
            date_format("month_start_date", "yyyy-MM").alias("year_month"),
            coalesce(col("order_count"), lit(0)).alias("order_count"),
            coalesce(col("total_quantity"), lit(0)).alias("total_quantity"),
        )
        .orderBy("month_start_date")
    )
# COMMAND ----------
# MAGIC ## `serve.purchase_trend_monthly`
# MAGIC 
# MAGIC Monthly purchase order volume across the full order history (line chart).
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.purchase_trend_monthly",
    comment="Monthly purchase order count and quantity for dashboard trend charts",
    table_properties={"quality": "gold", "domain": "procurement"},
)
def serve_purchase_trend_monthly():
    purchase_orders = (
        spark.read.table(f"{REFINED}.purchase_orders")
        .filter(col("status") != "CANCELLED")
        .filter(col("order_date").isNotNull())
    )

    bounds = purchase_orders.agg(
        spark_min(trunc("order_date", "month")).alias("min_month"),
        spark_max(trunc("order_date", "month")).alias("max_month"),
    )
    months = _full_month_spine(bounds)

    monthly_totals = (
        purchase_orders.withColumn("month_start_date", trunc("order_date", "month"))
        .groupBy("month_start_date")
        .agg(
            count(lit(1)).alias("order_count"),
            spark_sum("quantity").alias("total_quantity"),
        )
    )

    return (
        months.join(monthly_totals, on="month_start_date", how="left")
        .select(
            col("month_start_date"),
            date_format("month_start_date", "yyyy-MM").alias("year_month"),
            coalesce(col("order_count"), lit(0)).alias("order_count"),
            coalesce(col("total_quantity"), lit(0)).alias("total_quantity"),
        )
        .orderBy("month_start_date")
    )
# COMMAND ----------
# MAGIC ## `serve.top_selling_materials`
# MAGIC 
# MAGIC Top finished goods by sold quantity (bar chart).
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.top_selling_materials",
    comment="Top finished goods ranked by sold quantity for dashboard bar charts",
    table_properties={"quality": "gold", "domain": "sales"},
)
def serve_top_selling_materials():
    sales_orders = spark.read.table(f"{REFINED}.sales_orders").filter(
        col("status") != "CANCELLED"
    )
    materials = spark.read.table(f"{REFINED}.materials").filter(
        col("material_type") == "FINISHED_GOOD"
    )

    sold_by_material = sales_orders.groupBy("material_id").agg(
        spark_sum("quantity").alias("sold_quantity"),
    )

    ranked = (
        sold_by_material.join(materials, on="material_id", how="inner")
        .withColumn(
            "sales_rank",
            row_number().over(Window.orderBy(col("sold_quantity").desc(), col("material_id"))),
        )
        .filter(col("sales_rank") <= TOP_SELLING_MATERIALS_LIMIT)
    )

    return ranked.select(
        "sales_rank",
        "material_id",
        "material_name",
        "material_type",
        "sold_quantity",
    ).orderBy("sales_rank")
# COMMAND ----------
# MAGIC ## `serve.material_procurement_trend_monthly`
# MAGIC 
# MAGIC Monthly material-level procurement, sales, and production consumption metrics for the material procurement dashboard.
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.material_procurement_trend_monthly",
    comment="Monthly PO/SO and production quantities by material for procurement dashboards",
    table_properties={"quality": "gold", "domain": "procurement"},
)
def serve_material_procurement_trend_monthly():
    purchase_orders = (
        spark.read.table(f"{REFINED}.purchase_orders")
        .filter(col("status") != "CANCELLED")
        .filter(col("order_date").isNotNull())
    )
    sales_orders = (
        spark.read.table(f"{REFINED}.sales_orders")
        .filter(col("status") != "CANCELLED")
        .filter(col("order_date").isNotNull())
    )
    production_output = spark.read.table(f"{REFINED}.production_output")
    production_orders = (
        spark.read.table(f"{REFINED}.production_orders")
        .filter(col("status") != "CANCELLED")
    )
    materials = spark.read.table(f"{REFINED}.materials")

    po_monthly = (
        purchase_orders.withColumn("month_start_date", trunc("order_date", "month"))
        .groupBy("material_id", "month_start_date")
        .agg(
            count(lit(1)).alias("purchase_order_count"),
            spark_sum("quantity").alias("purchase_quantity"),
        )
    )

    so_monthly = (
        sales_orders.withColumn("month_start_date", trunc("order_date", "month"))
        .groupBy("material_id", "month_start_date")
        .agg(
            count(lit(1)).alias("sales_order_count"),
            spark_sum("quantity").alias("sales_quantity"),
        )
    )

    production_with_month = (
        production_output.join(
            production_orders.select("production_order_id", "start_date", "end_date"),
            on="production_order_id",
            how="inner",
        )
        .withColumn(
            "month_start_date",
            trunc(coalesce(col("end_date"), col("start_date")), "month"),
        )
        .filter(col("month_start_date").isNotNull())
    )

    input_monthly = production_with_month.groupBy(
        col("input_material_id").alias("material_id"),
        "month_start_date",
    ).agg(spark_sum("input_quantity").alias("production_input_quantity"))

    output_monthly = production_with_month.groupBy(
        col("output_material_id").alias("material_id"),
        "month_start_date",
    ).agg(spark_sum("output_quantity").alias("production_output_quantity"))

    material_months = (
        po_monthly.select("material_id", "month_start_date")
        .union(so_monthly.select("material_id", "month_start_date"))
        .union(input_monthly.select("material_id", "month_start_date"))
        .union(output_monthly.select("material_id", "month_start_date"))
        .distinct()
    )

    return (
        material_months.join(
            materials.select("material_id", "material_name", "material_type"),
            on="material_id",
            how="inner",
        )
        .join(po_monthly, on=["material_id", "month_start_date"], how="left")
        .join(so_monthly, on=["material_id", "month_start_date"], how="left")
        .join(input_monthly, on=["material_id", "month_start_date"], how="left")
        .join(output_monthly, on=["material_id", "month_start_date"], how="left")
        .select(
            "material_id",
            "material_name",
            "material_type",
            "month_start_date",
            date_format("month_start_date", "yyyy-MM").alias("year_month"),
            coalesce(col("purchase_order_count"), lit(0)).alias("purchase_order_count"),
            coalesce(col("purchase_quantity"), lit(0)).alias("purchase_quantity"),
            coalesce(col("sales_order_count"), lit(0)).alias("sales_order_count"),
            coalesce(col("sales_quantity"), lit(0)).alias("sales_quantity"),
            coalesce(col("production_input_quantity"), lit(0)).alias("production_input_quantity"),
            coalesce(col("production_output_quantity"), lit(0)).alias("production_output_quantity"),
        )
        .orderBy("material_id", "month_start_date")
    )
# COMMAND ----------
# MAGIC ## `serve.production_order_summary`
# MAGIC 
# MAGIC Production order counts and quantities by plant and status.
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.production_order_summary",
    comment="Production order volume and quantities by plant and status",
    table_properties={"quality": "gold", "domain": "mes"},
)
def serve_production_order_summary():
    production_orders = spark.read.table(f"{REFINED}.production_orders")
    plants = spark.read.table(f"{REFINED}.plants")

    return (
        production_orders.join(plants, on="plant_id", how="inner")
        .groupBy(
            col("plant_id"),
            col("plant_name"),
            col("status"),
        )
        .agg(
            count(lit(1)).alias("order_count"),
            spark_sum("planned_quantity").alias("planned_quantity"),
            coalesce(spark_sum("actual_quantity"), lit(0)).alias("actual_quantity"),
        )
    )
# COMMAND ----------
# MAGIC ## `serve.production_trend_monthly`
# MAGIC 
# MAGIC Monthly production order volume across the full production history.
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.production_trend_monthly",
    comment="Monthly production order count and planned/actual quantities",
    table_properties={"quality": "gold", "domain": "mes"},
)
def serve_production_trend_monthly():
    production_orders = (
        spark.read.table(f"{REFINED}.production_orders")
        .filter(col("status") != "CANCELLED")
        .withColumn(
            "production_month",
            trunc(coalesce(col("end_date"), col("start_date")), "month"),
        )
        .filter(col("production_month").isNotNull())
    )

    bounds = production_orders.agg(
        spark_min("production_month").alias("min_month"),
        spark_max("production_month").alias("max_month"),
    )
    months = _full_month_spine(bounds)

    monthly_totals = production_orders.groupBy(
        col("production_month").alias("month_start_date")
    ).agg(
        count(lit(1)).alias("order_count"),
        spark_sum("planned_quantity").alias("planned_quantity"),
        coalesce(spark_sum("actual_quantity"), lit(0)).alias("actual_quantity"),
    )

    return (
        months.join(monthly_totals, on="month_start_date", how="left")
        .select(
            col("month_start_date"),
            date_format("month_start_date", "yyyy-MM").alias("year_month"),
            coalesce(col("order_count"), lit(0)).alias("order_count"),
            coalesce(col("planned_quantity"), lit(0)).alias("planned_quantity"),
            coalesce(col("actual_quantity"), lit(0)).alias("actual_quantity"),
        )
        .orderBy("month_start_date")
    )
# COMMAND ----------
# MAGIC ## `serve.machine_downtime_summary`
# MAGIC 
# MAGIC Machine downtime event counts and hours by plant, machine, and reason.
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.machine_downtime_summary",
    comment="Downtime event counts and total hours by plant, machine, and reason",
    table_properties={"quality": "gold", "domain": "mes"},
)
def serve_machine_downtime_summary():
    machine_downtime = spark.read.table(f"{REFINED}.machine_downtime")
    plants = spark.read.table(f"{REFINED}.plants")

    enriched = machine_downtime.withColumn(
        "downtime_hours",
        (unix_timestamp("end_time") - unix_timestamp("start_time")) / lit(3600.0),
    ).filter(col("downtime_hours") > 0)

    return (
        enriched.join(plants, on="plant_id", how="inner")
        .groupBy(
            col("plant_id"),
            col("plant_name"),
            col("machine_name"),
            col("reason"),
        )
        .agg(
            count(lit(1)).alias("downtime_event_count"),
            spark_sum("downtime_hours").alias("total_downtime_hours"),
        )
    )
# COMMAND ----------
# MAGIC ## `serve.machine_downtime_monthly`
# MAGIC 
# MAGIC Monthly downtime trends by plant and reason across the full event history.
# COMMAND ----------

@dp.materialized_view(
    name=f"{SERVE}.machine_downtime_monthly",
    comment="Monthly downtime event counts and hours by plant and reason",
    table_properties={"quality": "gold", "domain": "mes"},
)
def serve_machine_downtime_monthly():
    machine_downtime = spark.read.table(f"{REFINED}.machine_downtime")
    plants = spark.read.table(f"{REFINED}.plants")

    enriched = (
        machine_downtime.withColumn(
            "downtime_hours",
            (unix_timestamp("end_time") - unix_timestamp("start_time")) / lit(3600.0),
        )
        .withColumn("month_start_date", trunc("start_time", "month"))
        .filter(col("downtime_hours") > 0)
        .filter(col("month_start_date").isNotNull())
    )

    return (
        enriched.join(plants, on="plant_id", how="inner")
        .groupBy("plant_id", "plant_name", "month_start_date", "reason")
        .agg(
            count(lit(1)).alias("downtime_event_count"),
            spark_sum("downtime_hours").alias("total_downtime_hours"),
        )
        .select(
            "plant_id",
            "plant_name",
            "month_start_date",
            date_format("month_start_date", "yyyy-MM").alias("year_month"),
            "reason",
            "downtime_event_count",
            "total_downtime_hours",
        )
        .orderBy("plant_id", "month_start_date", "reason")
    )
