#!/usr/bin/env python3
"""Sync ldp_operations_transformations.py from the silver and gold pipeline notebooks."""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SILVER_NOTEBOOK = REPO_ROOT / "notebooks" / "ldp_silver_transformations.ipynb"
GOLD_NOTEBOOK = REPO_ROOT / "notebooks" / "ldp_gold_transformations.ipynb"
OUTPUT = REPO_ROOT / "ldp_operations_transformations.py"

COMBINED_HEADER = """# Databricks notebook source
# MAGIC %md
# MAGIC # Operations Transformation Pipeline (Combined Reference)
# MAGIC
# MAGIC Combined silver + gold Lakeflow Declarative Pipeline source of truth.
# MAGIC
# MAGIC | File | Purpose |
# MAGIC |------|---------|
# MAGIC | `notebooks/ldp_silver_transformations.ipynb` | Silver pipeline (deploy to Databricks) |
# MAGIC | `notebooks/ldp_gold_transformations.ipynb` | Gold pipeline (deploy to Databricks) |
# MAGIC | `ldp_operations_transformations.py` | Synced reference copy of both notebooks |
# MAGIC
# MAGIC **Do not edit this file directly.** Update the notebooks, then run:
# MAGIC
# MAGIC ```bash
# MAGIC python scripts/sync_ldp_operations_transformations.py
# MAGIC ```
# MAGIC
# MAGIC Architecture: Bronze (ingest) → Silver materialized views (`refined`) → Gold materialized views (`serve`).
"""

GOLD_ONLY_IMPORTS = [
    "count",
    "countDistinct",
    "max as spark_max",
    "sum as spark_sum",
]

# Gold notebook cells before the first materialized view (title, config, imports).
GOLD_PREFIX_CELL_COUNT = 5


def _cell_source(cell: dict) -> str:
    return "".join(cell.get("source", []))


def _cells_to_source(cells: list[dict]) -> list[str]:
    parts: list[str] = []
    for cell in cells:
        parts.append("# COMMAND ----------\n")
        if cell.get("cell_type") == "markdown":
            for line in _cell_source(cell).splitlines():
                parts.append(f"# MAGIC {line}\n")
        elif cell.get("cell_type") == "code":
            parts.append("\n")
            source = _cell_source(cell)
            parts.append(source)
            if not source.endswith("\n"):
                parts.append("\n")
    return parts


def _patch_silver_config(config_source: str) -> str:
    return config_source.replace(
        'REFINED = f"{CATALOG}.{REFINED_SCHEMA}"\n',
        'REFINED = f"{CATALOG}.{REFINED_SCHEMA}"\n'
        'SERVE_SCHEMA = "serve"\n\n'
        'SERVE = f"{CATALOG}.{SERVE_SCHEMA}"\n',
        1,
    )


def _patch_silver_imports(import_source: str) -> str:
    for item in GOLD_ONLY_IMPORTS:
        if item not in import_source:
            import_source = re.sub(
                r"(from pyspark\.sql\.functions import \(\n)",
                rf"\1    {item},\n",
                import_source,
                count=1,
            )
    return import_source


def _patch_silver_cells(cells: list[dict]) -> list[dict]:
    patched: list[dict] = []
    for cell in cells:
        if cell.get("cell_type") != "code":
            patched.append(cell)
            continue
        source = _cell_source(cell)
        if 'REFINED = f"{CATALOG}.{REFINED_SCHEMA}"' in source:
            source = _patch_silver_config(source)
        if "from pyspark.sql.functions import" in source:
            source = _patch_silver_imports(source)
        patched.append({**cell, "source": [source]})
    return patched


def build_combined_source() -> str:
    silver = json.loads(SILVER_NOTEBOOK.read_text())
    gold = json.loads(GOLD_NOTEBOOK.read_text())

    silver_body = _patch_silver_cells(silver["cells"][1:])
    gold_body = gold["cells"][GOLD_PREFIX_CELL_COUNT:]

    parts = [COMBINED_HEADER]
    parts.append("# COMMAND ----------\n")
    parts.append("# MAGIC %md\n")
    parts.append("# MAGIC ## Silver layer — `refined` schema\n")
    parts.extend(_cells_to_source(silver_body))

    parts.append("# COMMAND ----------\n")
    parts.append("# MAGIC %md\n")
    parts.append("# MAGIC ## Gold layer — `serve` schema\n")
    parts.extend(_cells_to_source(gold_body))

    return "".join(parts)


def main() -> None:
    OUTPUT.write_text(build_combined_source())
    print(f"Synced {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
